#!/usr/bin/env node
/**
 * One-command local setup for a fresh clone of the KIRO-GPT Bridge.
 *
 *   npm run setup
 *
 * Generates random shared secrets LOCALLY (they are never committed),
 * writes `.env` (gitignored) and `.kiro/settings/mcp.json`, detects the
 * system Chrome/Edge for the browser agent, and prints the next steps.
 *
 * There are deliberately NO credentials stored in this repository. The
 * ChatGPT session itself is kept in the browser agent's persistent
 * Chromium profile after a one-time manual login — nothing to save.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import * as process from 'node:process';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');

function generateSecret() {
  return crypto.randomBytes(24).toString('base64url');
}

function detectBrowser() {
  const candidates =
    process.platform === 'win32'
      ? [
          'C:/Program Files/Google/Chrome/Application/chrome.exe',
          'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
          process.env.LOCALAPPDATA
            ? `${process.env.LOCALAPPDATA}/Google/Chrome/Application/chrome.exe`
            : '',
          'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
        ]
      : process.platform === 'darwin'
        ? [
            '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
            '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
          ]
        : [
            '/usr/bin/google-chrome',
            '/usr/bin/google-chrome-stable',
            '/usr/bin/microsoft-edge',
            '/usr/bin/chromium-browser',
          ];
  for (const candidate of candidates) {
    if (candidate && fs.existsSync(candidate)) return candidate;
  }
  return '';
}

const envPath = path.join(repoRoot, '.env');

if (fs.existsSync(envPath) && !force) {
  console.log(`.env already exists at ${envPath} — keeping it. Re-run with --force to regenerate.`);
} else {
  const kiroSecret = generateSecret();
  const agentSecret = generateSecret();
  const browser = detectBrowser();
  const lines = [
    '# Generated by `npm run setup`. This file is gitignored — never commit it.',
    `KIRO_SECRET=${kiroSecret}`,
    `AGENT_SECRET=${agentSecret}`,
    '',
    'PORT=3001',
    'RELAY_URL=ws://localhost:3001',
    '',
    `AGENT_PROFILE_DIR=${repoRoot.replace(/\\/g, '/')}/.agent-profile`,
    '',
    `KIRO_GPT_MCP_SECRET=${kiroSecret}`,
    'KIRO_GPT_MCP_RELAY_URL=ws://localhost:3001',
    '',
  ];
  if (browser) {
    lines.push(`# Real Chrome/Edge beats the downloaded Chrome-for-Testing build:`,);
    lines.push(`# Google's OAuth refuses sign-in from automation-flagged CfT builds.`);
    lines.push(`PUPPETEER_EXECUTABLE_PATH="${browser}"`);
    lines.push('');
  } else {
    console.log('Note: no system Chrome/Edge found — the agent will use puppeteer\u2019s Chromium.');
  }
  fs.writeFileSync(envPath, lines.join('\n'), 'utf8');
  console.log(`Wrote ${envPath}`);
}

// .kiro/settings/mcp.json — local MCP registration for Kiro (gitignored).
const kiroDir = path.join(repoRoot, '.kiro', 'settings');
const mcpJsonPath = path.join(kiroDir, 'mcp.json');
if (fs.existsSync(mcpJsonPath) && !force) {
  console.log(`.kiro/settings/mcp.json already exists — keeping it.`);
} else {
  const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
  const mcpConfig = {
    mcpServers: {
      'kiro-gpt-bridge': {
        command: 'node',
        args: ['./mcp-server/dist/index.js'],
        env: {
          KIRO_GPT_MCP_SECRET: env.KIRO_SECRET,
          KIRO_GPT_MCP_RELAY_URL: 'ws://localhost:3001',
        },
        disabled: false,
        autoApprove: [
          'generate_image',
          'generate_logo',
          'generate_hero',
          'generate_icon_set',
          'generate_ui_mockup',
          'generate_banner',
          'generate_og_image',
          'generate_icon_3d',
          'analyze_design',
        ],
      },
    },
  };
  fs.mkdirSync(kiroDir, { recursive: true });
  fs.writeFileSync(mcpJsonPath, JSON.stringify(mcpConfig, null, 2), 'utf8');
  console.log(`Wrote ${mcpJsonPath}`);
}

console.log('');
console.log('Setup complete. Next steps:');
console.log('  1. npm run build      (skip if already built)');
console.log('  2. npm run doctor     (health check)');
console.log('  3. start-relay.bat    (or: set -a; source .env; set +a; node relay-server/dist/index.js)');
console.log('  4. start-agent.bat    (opens a Chrome window — log into ChatGPT ONCE;');
console.log('                         the session persists in .agent-profile/)');
console.log('');
console.log('Secrets live only in .env (gitignored). Nothing sensitive is committed.');

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const m = /^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(line.trim());
    if (m) out[m[1]] = m[2];
  }
  return out;
}
